### ISSUE TITLE
Learn-SQL.html - Online tools for SQLite

### ISSUE THREAD

**Issue by cyrilbois** [bbkane/bbkane.github.io#1]
Hello,

about your article "/2017/10/10/Learn-SQL.html", there are also online tools for SQLite (without installation), including my tool (https://extendsclass.com/sqlite-browser.html), but there are also others (https://sqliteonline.com/). This might interest visitors to your article.

Have a good day.

**Comment by bbkane** [comment]
I have [Franchise](https://franchise.cloud/) up there, but I think I'll make a new section and add one of these. I want to call out that you can do real SQL-y things entirely from a browser. That's so cool! Thanks for the issue. Setting a reminder to do this after work...

**Comment by cyrilbois** [comment]
Sorry, I did not see "Franchise", I did not know it, it looks interesting!

**Comment by bbkane** [comment]
Updated the page - what do you think?

**Comment by cyrilbois** [comment]
It is great, thank you!
